### ISSUE TITLE
Show Coworking Spaces

### ISSUE THREAD

**Issue by s-zanker** [s-zanker/capstone-project#1]
## Value statement

**As a** digital nomad
**I need**  a list of coworking spaces
**so that** I can see possible places to work and socialize

## Description (Text, Scribble, Wireframe, Design)

- A nice list of coworking spaces

## Acceptance criteria

- [ ] coworking spaces are listed in a vertical row on main screen
- [ ] coworking spaces can be scrolled in vertical direction
- [ ] the name and the location of each coworking space are shown

## Tasks

- [ ] Create a list of coworking spaces
- [ ] Create initial styling
- [ ] Add a header that is sticky to the top

## Size
medium
