### ISSUE TITLE
Initial setup of react project

### ISSUE THREAD

**Issue by s-zanker** [s-zanker/capstone-project#2]
# Tasks

- [ ] Create React App
- [ ] Delete unused initial content from React App
- [ ] Configure package.json
- [ ] Add .gitignore
- [ ] Add .prettierrc
- [ ] Install: Storybook, Cypress, Styled Components, Prop Types
- [ ] Define Global Styles
- [ ] Connect to remote git repo

# Size

small
