### ISSUE TITLE
#3 Show details of a coworking space

### ISSUE THREAD

**Issue by s-zanker** [s-zanker/capstone-project#3]
## Value statement

**As a** seeker of coworking spaces
**I need** a description and the contact details of the selected coworking space
**so that** i can decide which coworking space i can choose to work at

## Description (Text, Scribble, Wireframe, Design)

- A coworking space page details page and the possibility to go back to the list of coworking spaces

![CoWoLi_page_02](https://user-images.githubusercontent.com/65186016/86396210-c9d29880-bca1-11ea-87e7-4cf7feffa390.jpg)

## Acceptance criteria

- [ ] coworking space is listed with name, description and contact details
- [ ] the page is scrollable in vertical direction, if the content doesn't fit on the screen
- [ ] the header sticks at the top, if the page is scrollable 
- [ ] there is a button or link that the user can touch to go back to list of all coworking spaces
- [ ] the user email clients will open, if the user has touched the email address

## Tasks

- [ ] add a new page with a coworking space and his details
- [ ] make the page scrollable if the content doesn't fit to the screen
- [ ] add a link to the coworking space component to navigate to this page
- [ ] add a link or button to go back to the list of all coworking spaces

## Size
medium
