### ISSUE TITLE
#4 Add a tag-list filter 

### ISSUE THREAD

**Issue by s-zanker** [s-zanker/capstone-project#6]
## Value statement

**As a** seeker of coworking spaces
**I need** a tag-list to filter the list of coworking spaces
**so that** i can find coworking spaces that offers what i am looking for

## Description (Text, Scribble, Wireframe, Design)

![digitalnatur_tag-filter_01](https://user-images.githubusercontent.com/65186016/87784882-6adf5880-c837-11ea-86b7-40fec3ce3340.jpg)

![digitalnatur_tag-filter_02](https://user-images.githubusercontent.com/65186016/87784901-7468c080-c837-11ea-8238-a974dde4eac3.jpg)

## Acceptance criteria

- [ ] there is a tag-filter button on top of the list of coworking spaces
- [ ] on click, a list of tags will be shown above the list of coworking spaces
- [ ] each tag can be selected or deselected again
- [ ] to filter the coworking spaces, you have to confirm the selected tags on click
- [ ] the tags represent features of the coworking spaces, the environment or the infrastructure
- [ ] tag examples: Garten, Wald, See, Kanufahren, Wandern, Reiten, Fahrradfahren, Übernachtung, Retreat
- [ ] tag categories: Freizeitangebote, Infrastruktur, Ausstattung, Service

## Tasks

- [ ] add a tag-filter button
- [ ] create a tag-list

## Size
medium
