### ISSUE TITLE
#4 Add tags to coworking spaces

### ISSUE THREAD

**Issue by s-zanker** [s-zanker/capstone-project#8]
## Value statement

**As a** seeker of coworking spaces
**I need** tags
**so that** i can see at a glance what the coworking space is about

## Description (Text, Scribble, Wireframe, Design)

![digitalnatur_tags_01](https://user-images.githubusercontent.com/65186016/88054916-6d56f080-cb5e-11ea-8dc9-a4243576e7c6.jpg)

![digitalnatur_tags_02](https://user-images.githubusercontent.com/65186016/88054937-76e05880-cb5e-11ea-8516-753526009826.jpg)

## Acceptance criteria

- [ ] tags should appear on the detail page and 
- [ ] tags will be shown under the website url at the coworking space list and the detail page
- [ ] tags are always listed in a row
- [ ] the tags represent special features of the coworking spaces, the environment or the infrastructure
- [ ] tags can be of the following categories: Freizeitangebote, Infrastruktur, Ausstattung, Service
- [ ] tag examples are: Garten, Wald, See, Kanufahren, Wandern, Reiten, Fahrradwege, Übernachtung, Heuboden, Retreat, CoLiving

## Tasks

- [ ] Create feature branch
- [ ] Add a button component 
- [ ] Add a tag-list component
- [ ] Create the tag list
- [ ] Add tag-list filter function

## Size
medium
